### ISSUE TITLE
Tests compare files paths are absolute

### ISSUE THREAD

**Issue by ichko** [valkone/hack_assembler#1]
Please fix the absolute paths to the compare files in the unt tests.
"C:/Users/valentin.tronkov/Desktop/nand2tetris/projects/06/rect/Rect.asm"

**Comment by valkone** [comment]
You are free to create PR, my friend :)

**Comment by valkone** [comment]
The fix is done. Thanks

**Comment by ichko** [comment]
This is not how you "fix" issues, "my friend".
